# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lsrm_min_cpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, option = TRUE, cores = 1L) {
    .Call('_lsrm_lsrm_min_cpp', PACKAGE = 'lsrm', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, option, cores)
}

lsrm_ms_cpp <- function(data, nsample, nitem, ndim, nset, nsamp_max, nitem_max, ntotal_max, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, pr_z_times, option = TRUE, cores = 1L) {
    .Call('_lsrm_lsrm_ms_cpp', PACKAGE = 'lsrm', data, nsample, nitem, ndim, nset, nsamp_max, nitem_max, ntotal_max, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, pr_z_times, option, cores)
}

lsrm_ms_eq_cpp <- function(data, nsample, nitem, ndim, nset, nsamp_max, nitem_max, ntotal_max, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, pr_z_times, option = TRUE, cores = 1L) {
    .Call('_lsrm_lsrm_ms_eq_cpp', PACKAGE = 'lsrm', data, nsample, nitem, ndim, nset, nsamp_max, nitem_max, ntotal_max, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, pr_z_times, option, cores)
}

lsrm_norm_cpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, pr_z_times, option = TRUE, cores = 1L) {
    .Call('_lsrm_lsrm_norm_cpp', PACKAGE = 'lsrm', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, pr_z_times, option, cores)
}

lsrm_norm_eq_cpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, option = TRUE, cores = 1L) {
    .Call('_lsrm_lsrm_norm_eq_cpp', PACKAGE = 'lsrm', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_sd_z, pr_mean_w, pr_sd_w, option, cores)
}

